# Site settings
title: Dr. Štěpán Sršeň
email: stepan.srsen@vscht.cz
url: https://stepan-srsen.github.io # the base hostname & protocol for your site, e.g. http://example.com
description: "Academic portfolio of Dr. Štěpán Sršeň"
keywords: "machine learning, artificial intelligence, quantum chemistry, computational chemistry, physical chemistry, photochemistry"
skills: "Quantum and Computational Chemist - Cheminformatician - Machine Learning Scientist"
meta_author: Sršeň Štěpán

# Content settings, ({{ section.id }}.html must exist in the _includes folder)
sections:
  - title: Topics
    id: topics
  - title: About
    id: about
  - title: Publications
    id: publications

# Jekyll Scholar settings
scholar:
  locale: en
  style: ./_bib/acs
  #style: american-chemical-society
  source: ./_bib
  bibliography: bibliography.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending
  bibtex_skip_fields: # which bibtex field not to show
    - abstract # default in jekyll-scholar
    - month_numeric # default in jekyll-scholar
    - file
  query: "@*" # all entries
  highlight: "Sršeň, Š" # to highlight in the bibilography

# Footer settings
footer:
  headline1: Office
  headline2: Around the Web
  headline3: Affiliation
  copyright: Štěpán Sršeň

# Postal address (add as many lines as necessary)
address:
  - line: "Phone: +420 220445039"
  - line: Office C115
  - line: Studentská 2031/6
  - line: 160 00 Prague 6, Czech Republic

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/stepan-srsen/
  - title: bluesky
    url: https://bsky.app/profile/stepansrsen.bsky.social
  - title: github
    url: http://github.com/stepan-srsen
  - title: orcid
    url: https://orcid.org/0000-0001-7723-4540

affiliation:
  - line: University of Chemistry and Technology, Prague
    url: https://www.vscht.cz
  - line: Department of Mathematics, Informatics and Cybernetics
    url: https://umik.vscht.cz
  - line: Technická 5
  - line: 166 28 Prague 6, Czech Republic

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  projects:
    output: false
    sort_by: modal-id

cv:
  - when: since 10/2025
    title: Assistant Professor
    where: University of Chemistry and Technology, Prague, Czech Republic
    descr:
      - 'Department: <i>Department of Mathematics, Informatics and Cybernetics</i>'
  - when: 10/2024-09/2025
    title: Postdoctoral Research Fellow
    where: University of Chemistry and Technology, Prague, Czech Republic
    descr:
      - 'research group: <i>independent postdoc position</i>'
      - 'fellowship: <i>Czech Science Foundation fellow</i>'
  - when: 10/2022-09/2024
    title: Postdoctoral Research Fellow
    where: University of Vienna, Austria
    descr:
      - 'research group: <i>Prof. Leticia González</i>'
      - 'fellowship: <i>Czech Science Foundation fellow</i>'
  - when: 01/2022-09/2022
    title: Postdoctoral Researcher
    where: University of Chemistry and Technology, Prague, Czech Republic
    descr:
      - 'research group: <i>Prof. Petr Slavíček</i>'
  - when: 09/2017-12/2021
    title: Ph.D. in Physical Chemistry
    where: University of Chemistry and Technology, Prague, Czech Republic
    descr:
      - 'thesis title: <i>Data Science Approach to Electronic Spectroscopy</i>'
      - 'supervisor: <i>Prof. Petr Slavíček</i>'
      - part of International Max Planck Research School
  - when: 11/2020-1/2021
    title: Research Stay
    where: University of Vienna, Austria
    descr:
      - 'research group: <i>Prof. Anatole von Lilienfeld</i>'
  - when: 2017-2019
    title: M.Sc. in Artificial Intelligence
    where: Czech Technical University in Prague, Czech Republic
    descr:
      - 'thesis title: <i>Development of molecular representations suitable for machine learning application in quantum chemistry and spectroscopy</i>'
      - 'supervisor: <i>Prof. Filip Železný</i>'
  - when: 2015-2017
    title: M.Sc. in Molecular Analytical and Physical Chemistry
    where: University of Chemistry and Technology, Prague, Czech Republic
    descr:
      - 'thesis title: <i>Criegee intermediates: Advanced simulations of electronic spectra and photodynamics</i>'
      - 'supervisor: <i>Prof. Petr Slavíček</i>'
      - graduated with honours
  - when: 2013-2017
    title: B.Sc. in Information Technology
    where: Czech Technical University in Prague, Czech Republic
    descr:
      - 'thesis title: <i>A distributed infrastructure for virtual molecule screening</i>'
      - 'supervisor: <i>Dr. Jan Starý</i>'
      - "Dean's Award for an extraordinary bachelor's thesis"
  - when: 2012-2015
    title: B.Sc. in Chemistry
    where: University of Chemistry and Technology, Prague, Czech Republic
    descr:
      - 'thesis title: <i>Spectroscopy of reactive atmospheric particles: Theoretical study of Criegee intermediate</i>'
      - 'supervisor: <i>Prof. Petr Slavíček</i>'
      - graduated with honours